Initialize cluster agent
canonical/microk8s-cluster-agent pull request #1
Opened 2022-03-24 16:50 UTC by neoaggelos

2022-03-25 07:00 UTC, AlexsJones requested changes

2022-03-25 07:00 UTC, AlexsJones commented on cmd/root.go
> +		bind, _ := cmd.Flags().GetString("bind")
It might be more idiomatic to use `rootCmd.Flags().StringVarP(&bind...` rather than have to skip an empty return option.

2022-03-25 07:00 UTC, AlexsJones commented on cmd/root.go
> +		log.Printf("Starting cluster agent on https://%s\n", bind)
Can we please use a structured logging library? https://github.com/sirupsen/logrus for example

2022-03-25 07:00 UTC, AlexsJones commented on pkg/util/kubectl.go
> +	Items []struct {
The formatting looks a bit off here

2022-03-25 07:00 UTC, AlexsJones commented on pkg/util/paths.go
> +	Snap string
These could be private fields

2022-03-25 07:00 UTC, AlexsJones commented on pkg/util/remote.go
> +func GetRemoteHost(hostname string, remoteAddress string) string {
Does this work for dualstack?

2022-03-25 22:18 UTC, balchua commented
Do you think using `golangci-lint` https://github.com/golangci/golangci-lint is a good option?

2022-03-28 06:59 UTC, AlexsJones commented
I also do not see any prometheus integration https://prometheus.io/docs/guides/go-application/

Can we please at least have the default prometheus metrics handler added in?

Later on, we might want to start exposing metrics about addon count through this as a vector gauge or counter.

2022-03-29 07:25 UTC, ktsakalozos requested changes

2022-03-29 07:25 UTC, ktsakalozos commented on pkg/api/v2/join.go
> +		return nil, fmt.Errorf("failed to join the cluster: this is not an HA MicroK8s cluster")
Lets keep the same error message and the same http error code as we have in the python implementation.

2022-04-04 06:40 UTC, ktsakalozos approved these changes
LGTM +1 thank you @neoaggelos

2022-04-04 07:32 UTC, merged